package envwriter

import (
	"bufio"
	"fmt"
	"os"
	"sort"
	"strings"
	"time"
)

// Writer handles writing secrets to a .env file.
type Writer struct {
	path string
}

// New creates a new Writer targeting the given file path.
func New(path string) *Writer {
	return &Writer{path: path}
}

// Write writes the given secrets map to the .env file.
// If prefix is non-empty, only keys starting with prefix are written.
// An existing file is backed up before overwriting.
func (w *Writer) Write(secrets map[string]string, prefix string) error {
	if err := w.backup(); err != nil {
		return fmt.Errorf("backing up existing file: %w", err)
	}

	f, err := os.Create(w.path)
	if err != nil {
		return fmt.Errorf("creating file %q: %w", w.path, err)
	}
	defer f.Close()

	bw := bufio.NewWriter(f)
	fmt.Fprintf(bw, "# Generated by vaultpull on %s\n", time.Now().Format(time.RFC3339))

	keys := make([]string, 0, len(secrets))
	for k := range secrets {
		if prefix == "" || strings.HasPrefix(k, prefix) {
			keys = append(keys, k)
		}
	}
	sort.Strings(keys)

	for _, k := range keys {
		v := secrets[k]
		if strings.ContainsAny(v, " \t\n#") {
			v = fmt.Sprintf("%q", v)
		}
		fmt.Fprintf(bw, "%s=%s\n", k, v)
	}

	return bw.Flush()
}

// backup creates a timestamped copy of the existing .env file if it exists.
func (w *Writer) backup() error {
	if _, err := os.Stat(w.path); os.IsNotExist(err) {
		return nil
	}
	backupPath := fmt.Sprintf("%s.bak.%d", w.path, time.Now().Unix())
	input, err := os.ReadFile(w.path)
	if err != nil {
		return err
	}
	return os.WriteFile(backupPath, input, 0600)
}
